### ISSUE TITLE
Tic Tac toe code review

### ISSUE THREAD

**Issue by mpashka** [mpashka/vlad_education#1]
Общее впечатление - круто, намного лучше, чем я ожидал.

Ты использовал пару фукнций js про которые я не знал :).

Кстати - подход а ля WINNING_COMBINATIONS.some(function) может называться функциональным. Еще есть вариант использовать императивный подход - а ля
for (i = 0; i < array.length; i++) {
   const element = array[i];
}
Сейчас функциональный подход в тренде, да. Но про понятие императивности тоже стоит знать.
В какой-то момент надо почитать что такое функциональный и императивный подходы.

Все что я говорю может быть нерелевантно. Но лучше не спорить, а просто, например спросить, подумать и сделать выводы.

Вообще общий подход для написания кода - пиши так, чтобы было легче понять, чтобы легче модифицировать. Но понятие модифицировать (исправлять ошибки, добавлять функционал) очень растяжимое. Кто-то считает, что надо так писать, чтобы для добавления нового функционала не надо было исправлять старый код. Я придерживаюсь похода "не модифицируй - переписывай" - пока не нашел - потом найду статью на хабре.

Теперь что можно улучшить:
1) ты завязался на css классы - это смешение бизнес логики (js) и отображения (css). Почему это может быть плохо. Потому что часто css пишут одни люди, js - другие люди. И не факт, что, например названия классов будут такими, как ты ожидаешь. Вообще не факт, что икс и нолик будут ставиться классом. Это лучше разделить.
2) в принципе WINNING_COMBINATIONS - неплохое решение. Но есть пара минусов. Во-первых в этом массиве легко допустить ошибку и трудно ее найти. Во-вторых ты хардкодишь размер игры 3х3. Давай от этого избавимся и сделаем, чтобы размер поля можно было задавать программно. Или, если хочешь, чтобы была возможночть изменять размер поля.
Еще я бы использовал не сквозную нумерацию ячеек, а координатную - x,y - так все-таки проще.
3) чисто UX, к делу не относится. чей ход  как-то надо бы выделять, конец игры. Ну и выигрышную комбинацию подчеркивать.

мелочи:
4) 'let circleTurn' - если использовать начальное значение true/false, то будет понятно какой тип у переменной
5) endGame({1|2}) - используются т.н. magic constants - лучше так не делать. Как минимум завести константу, как максимум - осмысленный объект, который можно использовать в function endGame()
6) else swapTurns() - я могу быть совсем не прав, но обычно создают блоки, потому что отсутствие блока может привести к тому, что можно чего-то не заметить.
7) checkDraw() - это совсем мой нерелевантный комментарий, но на мой взгляд название слишком компрометирующее - не так много русскоговорящих программистов знают, что draw - это ничья. Еще в джаве, например, принято использовать префиксы для методов get / set / is - is для boolean.

Вообще "мелочи" как правило описываются в т.н. code conventions и определяются заранее. Ну или ты сам для себя в процессе формируешь какой-то единый стиль оформления, чтобы весь код был единообразным.

**Comment by Tionlierite** [comment]
1. ✓
2. ✓
3. WIP
4. ✓
5. ✓
6. ✓
7. ✓
